
import json
import random
import string
from pathlib import Path

class Bank:
    database=Path(__file__).parent/"data.json"
    data=[]
    try:
        if Path(database).exists():
            with open(database) as fs:
                data=json.loads(fs.read())

        else:
            print("no such file exist")
    except Exception as e:
        print(f"an exception occurred as {e}")

    @classmethod
    def __update(cls):
        with open(cls.database,'w') as fs:
            fs.write(json.dumps(cls.data))

    @classmethod
    def __account_generate(cls): 
        # in offical bank account number is generated by the bank and it contains only numbers but here we are generating it randomly with letters, numbers and special characters for the sake of learning
        alpha=random.choices(string.ascii_letters, k=3)
        num=random.choices(string.digits, k=3)
        sp_char=random.choices("!@#$%^&*", k=1)
        id=alpha+num+sp_char
        random.shuffle(id)
        return "".join(id)

    def Create_account(self):
        info={
            "name":input("tell your name : "),
            "age":int(input("tell your age : ")),
            "email":input("tell your email : "),
            "pin":input("tell your pin : "),
            "accountNo.":self.__account_generate(),
            "balance":0,
        }
        for i in info:
            print(f"{i} :{info[i]}")
        print("please note down your account number for future reference")
        Bank.data.append(info)
        Bank.__update()


    def Deposit_money(self):
        accnumber=input("enter your account number : ")
        pin=input("enter your pin : ")
        

        userdata=[i for i in Bank.data if i["accountNo."]==accnumber and i["pin"]==pin]

        if not userdata:
            print("sorry no such account exist")
        else:
            amount=int(input("enter amount you want to deposit : "))
            if amount>10000 or amount<0:
                print("sorry you can not deposit more than 10000 or less than 0")
            else:
                userdata[0]['balance']+=amount
                self.__update()
                print("Amount deposited succesfully")


    def Withdraw_money(self):
            accnumber=input("enter your account number : ")
            pin=input("enter your pin : ")
            
    
            userdata=[i for i in self.data if i["accountNo."]==accnumber and i["pin"]==pin]
    
            if not userdata:
                print("sorry no such account exist")
            else:
                amount=int(input("enter amount you want to withdraw : "))
                if amount<=0:
                    print("sorry you can not withdraw less than 0")
                if userdata[0]['balance']<amount:
                    print("sorry you can not withdraw more than your balance")
                else:
                    userdata[0]['balance']-=amount
                    self.__update()
                    print("Amount withdrawn succesfully")
    
    def Show_details(self):
        accnumber=input("enter your account number : ")
        pin=input("enter your pin : ")

        userdata=[i for i in self.data if i["accountNo."]==accnumber and i["pin"]==pin]
        print("your account details are as follows : \n\n")
        if not userdata:
            print("sorry no such account exist")
        else:
            for i in userdata[0]:
                print(f"{i} : {userdata[0][i]}")
        
    def Update_details(self):
        accnumber=input("please enter your account number : ")
        pin=input("please enter your pin : ")
        userdata=[i for i in Bank.data if i["accountNo."]==accnumber and i["pin"]==pin]
        
        if not userdata:
            print("sorry no such account exist")
        else:
            print("you cannot change the age, account number and balance")

            print("Fill the details for change or leave it empty if no change is needed")

            newdata={
                "name":input("please tell your name or press enter: "),
                "email":input("please tell your new Email or press enter to skip :"),
                "pin":input("enter new Pin or press enter to skip : "),
            }

            if newdata['name']=="":
                newdata['name']=userdata[0]['name']
            if newdata['email']=="":
                newdata['email']=userdata[0]['email']
            if newdata['pin']=="":
                newdata['pin']=userdata[0]['pin']
            
            newdata['age']=userdata[0]['age']
            newdata['accountNo.']=userdata[0]['accountNo.']
            newdata['balance']=userdata[0]['balance']

            if type(newdata['pin'])==str:
                newdata['pin']=int(newdata['pin'])

            for i in newdata:
                if newdata[i]==userdata[0][i]:
                    continue
                else:
                    userdata[0][i]=newdata[i]
            Bank.__update()
            print("your details have been updated succesfully")

    def Delete_account(self):
        accnumber=input("please enter your account number : ")
        pin=int(input("please enter your pin : "))
        userdata=[i for i in Bank.data if i["accountNo."]==accnumber and i["pin"]==pin]
        if not userdata:
            print("sorry no such account exist")
        else:
            check=input("are you sure you want to delete your account ? (y/n) : ")
            if check.lower()=="y":
                Bank.data.remove(userdata[0])
                Bank.__update()
                print("your account has been deleted succesfully")
            else:
                print("bypasses")

user=Bank()
print("press 1 for creating an account")
print("press 2 for Depositing money in the bank")
print("press 3 for withdrawing money from the bank")
print("press 4 for details")
print("press 5 for updating the details")
print("press 6 for deleting the account")
check=int(input("enter your choice : "))
if check==1:
    user.Create_account()

elif check==2:
    user.Deposit_money()

elif check==3:
    user.Withdraw_money()

elif check==4:
    user.Show_details()

elif check==5:
    user.Update_details()

elif check==6:
    user.Delete_account()